spring:
  application:
    name: yt-dlp-bot-Java

  datasource:
    username: postgres
    password: fenrirpro123
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/telegram-bot

  jpa:
    hibernate:
      ddl-auto: update


telegram:
  bot:
    username: ${BOT_USERNAME}
    token: ${BOT_TOKEN}
    owner_token: ${OWNER_TOKEN}
    owner_username: ${OWNER_USERNAME}

downloader:
  base_path: ${DOWNLOADS_DIRECTORY}