spring:
  application:
    name: yt-dlp-bot-Java

telegram:
  bot:
    username: ${BOT_USERNAME}
    token: ${BOT_TOKEN}
    owner_token: ${OWNER_TOKEN}
    owner_username: ${OWNER_USERNAME}

downloader:
  base_path: ${DOWNLOADS_DIRECTORY}